name: Fetch&Push Latest Risk Data

on:
  schedule:
    - cron: "0 */4 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Sync Risk Data
        run: |
          git checkout api
          git checkout main
          git checkout api -- *.json
          mkdir Archive
          mv *.json ./Archive

      - name: Fetch and Save Latest Risk Data
        run: |
          if python risklevel.py; then
            echo "push_required=1" >> $GITHUB_ENV;
            echo "Updated risk data successfully.";
          else
            echo "No update required.";
          fi

      - name: Push to api Branch
        if: env.push_required == 1
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: api
          FOLDER: Archive
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Update: ({sha}) {date}"
